project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!drafts/"

website:
  title: "Melinda Higgins - Website Built with Quarto"
  site-url: https://melindahiggins2.netlify.app/
  description: "Melinda Higgins Website and Blog"
  favicon: favicon-32x32.png
  navbar:
    title: Melinda Higgins
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
      - href: posts.qmd
        text: Blog
    right:
      - href: cv/HigginsCV_16June2023_noHighlights.pdf
        text: CV
      - icon: github
        href: https://github.com/melindahiggins2000
      - icon: rss
        href: posts.xml
  page-footer:
    background: light
    left:
      - "Copyright 2024, Melinda Higgins, PhD."

format:
  html:
    theme: 
      - yeti
      - mkh_styles.scss
    mainfont: Nunito
    toc: true
    page-layout: full



